let header = [
    { label: "用户号码", prop: "msisdn"},
    { label: "4/5g标签", prop: "label45g"},
    { label: "MR总次数", prop: "mrAll"},
    { label: "RSRP>-110次数", prop: "rsrp_110_cnt"},
    { label: "平均RSRP", prop: "rsrp"},
    { label: "平均RSRQ", prop: "rsrq"},
    { label: "平均SINR", prop: "sinr"},
    { label: "平均TA", prop: "ta"},
]
let header2 = [
    { label: '小时级', prop: 'sdate' },
    { label: '原始时间', prop: 'orig_time' },
    { label: '用户号码', prop: 'msisdn' },
    { label: '用户识别码', prop: 'imsi' },
    { label: '服务小区号', prop: 'ci' },
    { label: '服务小区名', prop: 'cell_name' },
    { label: '45G标签', prop: 'label45g' },
    { label: '服务小区频点号', prop: 'arfcn' },
    { label: '服务小区的物理小区识别码', prop: 'pci' },
    { label: '服务小区RSRP', prop: 'rsrp' },
    { label: '服务小区RSRQ', prop: 'rsrq' },
    { label: '服务小区TA', prop: 'ta' },
    { label: '服务小区sinr', prop: 'sinr' },
    { label: '经度', prop: 'longitude' },
    { label: '纬度', prop: 'latitude' },
    { label: 'NR邻区1频点号', prop: 'ncell1_arfcn' },
    { label: 'NR邻区1的物理小区识别码', prop: 'ncell1_pci' },
    { label: 'NR邻区1的SSB参考信号接收功率', prop: 'ncell1_ssb_rsrp' },
    { label: 'NR邻区1的SSB参考信号接收质量', prop: 'ncell1_ssb_rsrq' },
    { label: 'NR邻区1的SSB波束号', prop: 'ncell1_ssb_beam_indexid' },
    { label: 'LTE邻区1频点号', prop: 'lte_ncell1_arfcn' },
    { label: 'LTE邻区1的物理小区识别码', prop: 'lte_ncell1_pci' },
    { label: 'LTE邻区1的参考信号接收功率', prop: 'lte_ncell1_rsrp' },
    { label: 'LTE邻区1的参考信号接收质量', prop: 'lte_ncell1_rsrq' },
    { label: 'NR邻区2频点号', prop: 'ncell2_arfcn' },
    { label: 'NR邻区2的物理小区识别码', prop: 'ncell2_pci' },
    { label: 'NR邻区2的SSB参考信号接收功率', prop: 'ncell2_ssb_rsrp' },
    { label: 'NR邻区2的SSB参考信号接收质量', prop: 'ncell2_ssb_rsrq' },
    { label: 'NR邻区2的SSB波束号', prop: 'ncell2_ssb_beam_indexid' },
    { label: 'LTE邻区2频点号', prop: 'lte_ncell2_arfcn' },
    { label: 'LTE邻区2的物理小区识别码', prop: 'lte_ncell2_pci' },
    { label: 'LTE邻区2的参考信号接收功率', prop: 'lte_ncell2_rsrp' },
    { label: 'LTE邻区2的参考信号接收质量', prop: 'lte_ncell2_rsrq' },
    { label: 'NR邻区3频点号', prop: 'ncell3_arfcn' },
    { label: 'NR邻区3的物理小区识别码', prop: 'ncell3_pci' },
    { label: 'NR邻区3的SSB参考信号接收功率', prop: 'ncell3_ssb_rsrp' },
    { label: 'NR邻区3的SSB参考信号接收质量', prop: 'ncell3_ssb_rsrq' },
    { label: 'NR邻区3的SSB波束号', prop: 'ncell3_ssb_beam_indexid' },
    { label: 'LTE邻区3频点号', prop: 'lte_ncell3_arfcn' },
    { label: 'LTE邻区3的物理小区识别码', prop: 'lte_ncell3_pci' },
    { label: 'LTE邻区3的参考信号接收功率', prop: 'lte_ncell3_rsrp' }
  ]